
import React, { useRef, useState } from 'react';
import { Download, FileText, Loader2 } from 'lucide-react';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

// Declare KaTeX on window object since it's loaded via CDN
declare global {
    interface Window {
        katex: any;
    }
}

interface MarkdownRendererProps {
    content: string;
    className?: string;
    baseTextSize?: string;
    baseTextColor?: string;
    showExport?: boolean;
    title?: string;
}

export const MarkdownRenderer: React.FC<MarkdownRendererProps> = ({ 
    content, 
    className = '',
    baseTextSize = 'text-sm md:text-base',
    baseTextColor = 'text-slate-300',
    showExport = true,
    title = 'AI_Response'
}) => {
    const contentRef = useRef<HTMLDivElement>(null);
    const [isExporting, setIsExporting] = useState(false);

    if (!content) return null;

    const handleDownloadPdf = async () => {
        if (!contentRef.current) return;
        setIsExporting(true);

        try {
            const element = contentRef.current;
            
            // Create a temporary container for printing to ensure good styling
            const printContainer = document.createElement('div');
            printContainer.style.position = 'fixed';
            printContainer.style.left = '-9999px';
            printContainer.style.top = '0';
            printContainer.style.width = '800px'; // Standard A4 width-ish
            printContainer.style.padding = '40px';
            printContainer.style.backgroundColor = '#0f172a'; // Match app background
            printContainer.style.color = '#cbd5e1';
            printContainer.style.fontFamily = 'sans-serif';
            
            // Clone the content
            const clone = element.cloneNode(true) as HTMLElement;
            
            // Remove the download button from the clone if it exists
            const downloadBtn = clone.querySelector('.pdf-export-btn');
            if (downloadBtn) downloadBtn.remove();
            
            // Add a header to the PDF
            const header = document.createElement('div');
            header.innerHTML = `
                <div style="border-bottom: 2px solid #334155; margin-bottom: 20px; padding-bottom: 10px;">
                    <h1 style="color: #38bdf8; margin: 0; font-size: 24px;">${title.replace(/_/g, ' ')}</h1>
                    <p style="color: #94a3b8; margin: 5px 0 0; font-size: 12px;">Generated by AI Assistant on ${new Date().toLocaleString()}</p>
                </div>
            `;
            printContainer.appendChild(header);
            printContainer.appendChild(clone);
            document.body.appendChild(printContainer);

            const canvas = await html2canvas(printContainer, {
                scale: 2,
                useCORS: true,
                backgroundColor: '#0f172a',
                logging: false,
            });

            const imgData = canvas.toDataURL('image/png');
            const pdf = new jsPDF({
                orientation: 'portrait',
                unit: 'px',
                format: [canvas.width / 2, canvas.height / 2]
            });

            const imgProps = pdf.getImageProperties(imgData);
            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

            pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
            pdf.save(`${title.replace(/\s+/g, '_')}_${new Date().getTime()}.pdf`);

            document.body.removeChild(printContainer);
        } catch (error) {
            console.error('PDF Export failed:', error);
        } finally {
            setIsExporting(false);
        }
    };

    const renderInline = (text: string) => {
        // Updated Regex for better matching:
        // 1. Code: `...`
        // 2. Block Math: $$...$$
        // 3. Inline Math: $...$
        // 4. Bold: **...** (Using .*? for non-greedy match allowing internal characters)
        // 5. Italic: *...*
        const parts = text.split(/(`[^`]+`|\$\$[^$]+\$\$|\$[^$]+\$|\*\*.*?\*\*|\*[^*]+\*)/g).filter(Boolean);
        
        return parts.map((part, index) => {
            // Code
            if (part.startsWith('`') && part.endsWith('`')) {
                return <code key={index} className="bg-slate-800 text-amber-300 px-1.5 py-0.5 rounded text-xs font-mono border border-slate-700 shadow-sm">{part.slice(1, -1)}</code>;
            }
            // Block Math
            if (part.startsWith('$$') && part.endsWith('$$')) {
                const math = part.slice(2, -2);
                try {
                    if (window.katex) {
                        const html = window.katex.renderToString(math, { 
                            throwOnError: false, 
                            displayMode: true 
                        });
                        return <span key={index} dangerouslySetInnerHTML={{ __html: html }} className="block my-2 text-center" />;
                    }
                } catch (e) {
                    console.error("KaTeX error", e);
                }
                return <div key={index} className="font-mono text-cyan-200 bg-slate-900 p-2 rounded text-center">{math}</div>; // Fallback
            }
            // Inline Math
            if (part.startsWith('$') && part.endsWith('$')) {
                const math = part.slice(1, -1);
                try {
                    if (window.katex) {
                        const html = window.katex.renderToString(math, { 
                            throwOnError: false, 
                            displayMode: false 
                        });
                        return <span key={index} dangerouslySetInnerHTML={{ __html: html }} className="mx-1" />;
                    }
                } catch (e) {
                    console.error("KaTeX error", e);
                }
                return <span key={index} className="font-mono text-cyan-200">{part}</span>; // Fallback
            }
            // Bold
            if (part.startsWith('**') && part.endsWith('**') && part.length >= 4) {
                return <strong key={index} className="text-white font-bold tracking-wide">{part.slice(2, -2)}</strong>;
            }
            // Italic
            if (part.startsWith('*') && part.endsWith('*') && part.length >= 2) {
                return <em key={index} className="text-indigo-200 italic font-medium">{part.slice(1, -1)}</em>;
            }
            // Regular Text
            return <span key={index}>{part}</span>;
        });
    };

    const renderTable = (rows: string[], keyIndex: number) => {
        // Basic Markdown Table Parser
        if (rows.length < 2) return null; // Need at least header and separator

        // Filter out empty strings that result from split if there are leading/trailing pipes
        const cleanRow = (r: string) => {
            // Remove leading/trailing pipes if present
            let content = r.trim();
            if (content.startsWith('|')) content = content.substring(1);
            if (content.endsWith('|')) content = content.substring(0, content.length - 1);
            return content.split('|').map(c => c.trim());
        };

        const headers = cleanRow(rows[0]);
        // rows[1] is the separator line (e.g. |---|), skip it
        const bodyRows = rows.slice(2).map(cleanRow);

        return (
            <div key={`table-${keyIndex}`} className="overflow-x-auto my-4 rounded-lg border border-slate-700/50 shadow-sm">
                <table className="min-w-full text-sm text-left">
                    <thead className="bg-slate-800 text-slate-200 font-bold uppercase tracking-wider text-xs">
                        <tr>
                            {headers.map((h, idx) => (
                                <th key={idx} className="px-4 py-3 border-b border-slate-700 whitespace-nowrap bg-slate-800/80">{renderInline(h)}</th>
                            ))}
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-700/50 bg-slate-900/30 text-slate-300">
                        {bodyRows.map((row, rIdx) => (
                            <tr key={rIdx} className="hover:bg-slate-800/30 transition-colors">
                                {row.map((cell, cIdx) => (
                                    <td key={cIdx} className="px-4 py-2 border-r border-slate-700/30 last:border-r-0">{renderInline(cell)}</td>
                                ))}
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        );
    };

    const lines = content.split('\n');
    const elements: React.ReactNode[] = [];
    let listStack: React.ReactNode[] = [];
    let inList = false;
    let tableBuffer: string[] = [];
    let inTable = false;

    const flushList = (keyPrefix: number) => {
        if (listStack.length > 0) {
            elements.push(<ul key={`ul-${keyPrefix}`} className="space-y-2 my-4 pl-2">{listStack}</ul>);
            listStack = [];
        }
        inList = false;
    };

    const flushTable = (keyPrefix: number) => {
        if (tableBuffer.length > 0) {
            elements.push(renderTable(tableBuffer, keyPrefix));
            tableBuffer = [];
        }
        inTable = false;
    };

    lines.forEach((line, i) => {
        const trimmed = line.trim();
        
        // Handle Table Detection
        if (trimmed.startsWith('|')) {
            if (!inTable) {
                flushList(i); // Close any open list
                inTable = true;
            }
            tableBuffer.push(trimmed);
            return;
        } else if (inTable) {
            flushTable(i);
        }

        // Handle Injected HTML (e.g. Footer)
        if (trimmed.startsWith('<div')) {
             if (inList) flushList(i);
             elements.push(<div key={i} dangerouslySetInnerHTML={{ __html: line }} />);
             return;
        }

        // Handle Lists
        if (trimmed.startsWith('- ') || trimmed.startsWith('* ') || /^\d+\.\s/.test(trimmed)) {
            const isOrdered = /^\d+\.\s/.test(trimmed);
            const content = trimmed.replace(/^[-*]\s|^\d+\.\s/, '');
            
            listStack.push(
                <li key={`li-${i}`} className={`ml-4 pl-2 relative ${isOrdered ? 'list-decimal text-slate-400 marker:text-cyan-500 marker:font-bold' : 'list-none'}`}>
                    {!isOrdered && (
                        <span className="absolute left-[-1.2rem] top-[0.6rem] w-1.5 h-1.5 bg-cyan-500 rounded-full shadow-[0_0_8px_rgba(6,182,212,0.5)]"></span>
                    )}
                    <span className={`${baseTextColor} leading-relaxed block`}>{renderInline(content)}</span>
                </li>
            );
            inList = true;
            return;
        }

        // Close list if we encounter non-list item
        if (inList) flushList(i);

        // Headers
        if (trimmed.startsWith('###')) {
            elements.push(
                <h3 key={i} className="text-lg font-bold text-cyan-400 mt-6 mb-3 border-b border-slate-700/50 pb-2 flex items-center gap-2 group">
                    <span className="text-cyan-500/30 text-sm group-hover:text-cyan-500/60 transition-colors">#</span> 
                    {renderInline(trimmed.replace(/^#+\s/, ''))}
                </h3>
            );
        } else if (trimmed.startsWith('##')) {
            elements.push(
                <h2 key={i} className="text-xl font-bold text-white mt-8 mb-4 pb-2 border-b border-slate-600 flex items-center gap-2">
                    <span className="w-1 h-6 bg-cyan-500 rounded-full"></span>
                    {renderInline(trimmed.replace(/^#+\s/, ''))}
                </h2>
            );
        } 
        // Blockquotes
        else if (trimmed.startsWith('>')) {
            elements.push(
                <blockquote key={i} className="border-l-4 border-indigo-500 pl-4 py-3 my-5 bg-gradient-to-r from-indigo-900/20 to-transparent rounded-r-lg italic text-indigo-100/90 text-sm leading-relaxed shadow-sm">
                    <span className="text-indigo-400 font-bold mr-2">💡 Insight:</span>
                    {renderInline(trimmed.replace(/^>\s?/, ''))}
                </blockquote>
            );
        } 
        // Horizontal Rule
        else if (trimmed === '---' || trimmed === '***') {
            elements.push(<hr key={i} className="border-slate-700 my-6" />);
        }
        // Paragraphs
        else if (trimmed.length > 0) {
            // Simplified paragraph rendering to handle markdown keys correctly.
            // Previous key-value split logic was breaking bold tags like **Key:**
            elements.push(<p key={i} className={`${baseTextColor} ${baseTextSize} leading-relaxed my-2 font-normal tracking-wide`}>{renderInline(trimmed)}</p>);
        } else {
            // Empty line spacing
            elements.push(<div key={i} className="h-2"></div>);
        }
    });

    // Flush remaining structures
    if (inList) flushList(lines.length);
    if (inTable) flushTable(lines.length);

    return (
        <div className={`relative group/md ${className}`}>
            {showExport && (
                <button
                    onClick={handleDownloadPdf}
                    disabled={isExporting}
                    className="pdf-export-btn absolute -top-2 -right-2 p-1.5 bg-slate-800/80 hover:bg-cyan-600 text-slate-400 hover:text-white rounded-md border border-slate-700 shadow-lg transition-all opacity-0 group-hover/md:opacity-100 z-10 flex items-center gap-1.5 text-[10px] font-medium uppercase tracking-wider"
                    title="Download as PDF"
                >
                    {isExporting ? (
                        <Loader2 className="w-3 h-3 animate-spin" />
                    ) : (
                        <Download className="w-3 h-3" />
                    )}
                    <span>PDF</span>
                </button>
            )}
            <div ref={contentRef} className="font-sans">
                {elements}
            </div>
        </div>
    );
};
